# Generated by Django 4.0.5 on 2022-06-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='Style',
            new_name='style',
        ),
    ]
